import os

path = r"c:\Users\Naveen\Downloads\Ai_Recruitment_Talent_copilot\frontend\components\ai_floating_button.py"

content = '"""components/ai_floating_button.py - HirePilot AI Floating Button.\n\nFloating AI Assistant launcher button.\n"""\n\nimport streamlit as st\n\n\ndef render_floating_button() -> None:\n    """Render the floating AI Assistant button."""\n    if st.session_state.get("ai_assistant_open", False):\n        return\n\n    st.markdown(\n        """\n    <style>\n    .ai-float-btn {\n        position: fixed;\n        bottom: 24px;\n        right: 24px;\n        width: 60px;\n        height: 60px;\n        border-radius: 50%;\n        background: linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%);\n        border: none;\n        cursor: pointer;\n        display: flex;\n        align-items: center;\n        justify-content: center;\n        box-shadow: 0 4px 20px rgba(99, 102, 241, 0.4), 0 2px 8px rgba(0,0,0,0.1);\n        z-index: 9999;\n        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n        animation: aiPulse 2s infinite;\n    }\n    .ai-float-btn:hover {\n        transform: scale(1.1);\n        box-shadow: 0 8px 30px rgba(99, 102, 241, 0.5), 0 4px 12px rgba(0,0,0,0.15);\n    }\n    .ai-float-btn:active {\n        transform: scale(0.95);\n    }\n    @keyframes aiPulse {\n        0%, 100% {\n            box-shadow: 0 4px 20px rgba(99, 102, 241, 0.4), 0 2px 8px rgba(0,0,0,0.1);\n        }\n        50% {\n            box-shadow: 0 6px 25px rgba(99, 102, 241, 0.5), 0 4px 12px rgba(0,0,0,0.15);\n        }\n    }\n    .ai-float-btn svg {\n        width: 28px;\n        height: 28px;\n        color: white;\n    }\n    @media (prefers-color-scheme: dark) {\n        .ai-float-btn {\n            background: linear-gradient(135deg, #818CF8 0%, #A78BFA 100%);\n        }\n    }\n    </style>\n    """,\n        unsafe_allow_html=True,\n    )\n\n    st.markdown(\n        """\n    <button class="ai-float-btn" id="ai-float-btn"\n            aria-label="Open AI Assistant" title="Open AI Assistant">\n        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"\n             fill="none" stroke="currentColor" stroke-width="2"\n             stroke-linecap="round" stroke-linejoin="round">\n            <path d="M12 14C15.3137 14 18 11.3137 18 8C18 4.68629 15.3137 2 12 2C8.68629 2 6 4.68629 6 8C6 11.3137 8.68629 14 12 14Z"\n                  fill="white"/>\n            <circle cx="12" cy="10" r="3" fill="white"/>\n            <path d="M12 17v4" stroke="white" stroke-width="2"/>\n            <path d="M8 21h8" stroke="white" stroke-width="2"/>\n        </svg>\n    </button>\n    """,\n        unsafe_allow_html=True,\n    )\n\n    if st.button("AI", key="ai_assistant_toggle", help="Open AI Assistant"):\n        from frontend.services.assistant_service import toggle_assistant\n        toggle_assistant()\n        st.rerun()\n'

with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)

print("Written:", len(content), "chars")
